import { MD3LightTheme } from 'react-native-paper';

export const brandColors = {
  gold: '#C79A33',
  lightGold: '#F5EDDB',
  softGold: '#FBF7EC',
  deepGold: '#8A661D',
  black: '#111111',
  charcoal: '#24211B',
  white: '#FFFFFF',
} as const;

export const theme = {
  ...MD3LightTheme,
  roundness: 4,
  colors: {
    ...MD3LightTheme.colors,
    primary: brandColors.gold,
    onPrimary: brandColors.black,
    primaryContainer: brandColors.lightGold,
    onPrimaryContainer: brandColors.black,
    secondary: brandColors.black,
    onSecondary: brandColors.lightGold,
    secondaryContainer: brandColors.lightGold,
    onSecondaryContainer: brandColors.black,
    tertiary: brandColors.deepGold,
    onTertiary: brandColors.white,
    tertiaryContainer: brandColors.lightGold,
    onTertiaryContainer: brandColors.black,
    background: brandColors.white,
    surface: brandColors.white,
    surfaceVariant: brandColors.softGold,
    outline: '#9A7A35',
    error: brandColors.black,
    errorContainer: brandColors.lightGold,
    onError: brandColors.white,
    onErrorContainer: brandColors.black,
    onBackground: brandColors.black,
    onSurface: brandColors.black,
    onSurfaceVariant: brandColors.black,
    surfaceDisabled: 'rgba(199, 154, 51, 0.12)',
    onSurfaceDisabled: 'rgba(17, 17, 17, 0.38)',
    backdrop: 'rgba(17, 17, 17, 0.48)',
    inverseSurface: brandColors.black,
    inverseOnSurface: brandColors.lightGold,
    inversePrimary: brandColors.gold,
    shadow: brandColors.black,
    scrim: brandColors.black,
    surfaceTint: brandColors.gold,
    elevation: {
      level0: 'transparent',
      level1: brandColors.white,
      level2: brandColors.softGold,
      level3: '#F9F1DE',
      level4: '#F7EED8',
      level5: brandColors.lightGold,
    },
  },
};
